-- RAW LAYER (Source Data Simulation)
-- Purpose: Ingest raw data from source systems without modification.
-- Database: demo1_ecommerce_raw

DROP DATABASE IF EXISTS demo1_ecommerce_raw;
CREATE DATABASE demo1_ecommerce_raw;
USE demo1_ecommerce_raw;

-- 1. Raw Customers
CREATE TABLE raw_customers (
    id INT,
    full_name VARCHAR(100),
    city VARCHAR(50),
    state_code CHAR(2),
    created_at TIMESTAMP,
    channel_type VARCHAR(20) -- Web, App, Affiliate
);

-- 2. Raw Products
CREATE TABLE raw_products (
    id INT,
    name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10,2),
    vendor_id INT,
    stock_qty INT
);

-- 3. Raw Orders
CREATE TABLE raw_orders (
    order_id INT,
    customer_id INT,
    status VARCHAR(20),
    order_timestamp TIMESTAMP,
    approved_at TIMESTAMP,
    shipped_at TIMESTAMP,
    delivered_at TIMESTAMP,
    shipping_region_id INT
);

-- 4. Raw Order Items
CREATE TABLE raw_order_items (
    item_id INT,
    order_id INT,
    product_id INT,
    unit_price DECIMAL(10,2),
    quantity INT,
    discount_amount DECIMAL(10,2)
);

-- 5. Raw Payments
CREATE TABLE raw_payments (
    payment_id INT,
    order_id INT,
    payment_method VARCHAR(20),
    amount DECIMAL(10,2),
    payment_status VARCHAR(20),
    processed_at TIMESTAMP
);

-- 6. Raw Vendors
CREATE TABLE raw_vendors (
    vendor_id INT,
    vendor_name VARCHAR(100),
    country VARCHAR(50)
);

-- DATA GENERATION (Simulated Ingestion)
-- Using CTEs to generate realistic enterprise-scale data structure

INSERT INTO raw_customers (id, full_name, city, state_code, created_at, channel_type)
SELECT n, CONCAT('Enterprise_Cust_', n), 
       ELT((n%5)+1, 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'),
       ELT((n%5)+1, 'NY', 'CA', 'IL', 'TX', 'AZ'),
       DATE_SUB(NOW(), INTERVAL (n%500) DAY),
       ELT((n%3)+1, 'Web', 'Mobile App', 'Affiliate')
FROM (SELECT a.N+b.N*10+c.N*100+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c) t;

INSERT INTO raw_products (id, name, category, price, vendor_id, stock_qty)
SELECT n, CONCAT('Premium_Product_', n),
       ELT((n%5)+1, 'Electronics', 'Home & Kitchen', 'Beauty', 'Fashion', 'Sports'),
       ROUND(10 + (RAND() * 2000), 2),
       (n%50) + 1,
       (n%1000)
FROM (SELECT a.N+b.N*10+c.N*100+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) c) t;

INSERT INTO raw_vendors (vendor_id, vendor_name, country)
SELECT n, CONCAT('Global_Vendor_', n),
       ELT((n%5)+1, 'USA', 'China', 'Germany', 'Japan', 'India')
FROM (SELECT a.N+b.N*10+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b) t;

INSERT INTO raw_orders (order_id, customer_id, status, order_timestamp, approved_at, shipped_at, delivered_at, shipping_region_id)
SELECT n, (n%1000)+1,
       ELT((n%10)+1, 'delivered', 'delivered', 'delivered', 'delivered', 'delivered', 'delivered', 'shipped', 'processing', 'cancelled', 'returned'),
       DATE_SUB(NOW(), INTERVAL (n%365) DAY),
       DATE_ADD(DATE_SUB(NOW(), INTERVAL (n%365) DAY), INTERVAL 1 HOUR),
       DATE_ADD(DATE_SUB(NOW(), INTERVAL (n%365) DAY), INTERVAL 1 DAY),
       DATE_ADD(DATE_SUB(NOW(), INTERVAL (n%365) DAY), INTERVAL 3 DAY),
       (n%50)+1
FROM (SELECT a.N+b.N*10+c.N*100+d.N*1000+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d) t;

INSERT INTO raw_order_items (item_id, order_id, product_id, unit_price, quantity, discount_amount)
SELECT n, (n%10000)+1, (n%500)+1,
       ROUND(50 + (RAND() * 500), 2),
       (n%5)+1,
       ROUND(RAND() * 20, 2)
FROM (SELECT a.N+b.N*10+c.N*100+d.N*1000+e.N*10000+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2) e) t;

INSERT INTO raw_payments (payment_id, order_id, payment_method, amount, payment_status, processed_at)
SELECT n, n,
       ELT((n%4)+1, 'Credit Card', 'UPI', 'Net Banking', 'Wallet'),
       ROUND(100 + (RAND() * 5000), 2),
       ELT((n%20=0)+1, 'success', 'failed'),
       DATE_SUB(NOW(), INTERVAL (n%365) DAY)
FROM (SELECT a.N+b.N*10+c.N*100+d.N*1000+1 n FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d) t;
